<a href="https://colab.research.google.com/github/Hyebeen-101903/AI_Programing/blob/main/%EC%9D%B8%EA%B3%B5%EC%A7%80%EB%8A%A5_%ED%94%84%EB%A1%9C%EA%B7%B8%EB%9E%98%EB%B0%8D_3%EC%A3%BC%EC%B0%A8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import tensorflow as tf
import torch


#dtype 변경

In [5]:
t = (1,2,3,4,5,6)

a= np.array(t)
a_tf = tf.constant(t)
a_torch = torch.tensor(t)

In [6]:
a1 = a_tf.numpy()
a2 = a_torch.numpy()

In [7]:
a3 = a_torch.numpy().copy()
a3[0] = 999
print(a3)
print(a_torch)


[999   2   3   4   5   6]
tensor([1, 2, 3, 4, 5, 6])


In [ ]:
a2[0] = 777
print(a2)
print(a_torch)

[777   2   3   4   5   6]
tensor([777,   2,   3,   4,   5,   6])


In [ ]:
print(a1)
print(a_tf)
a1[0] = 888
print(a1)
print(a_tf)

[1 2 3 4 5 6]
tf.Tensor([1 2 3 4 5 6], shape=(6,), dtype=int32)
[888   2   3   4   5   6]
tf.Tensor([1 2 3 4 5 6], shape=(6,), dtype=int32)


In [ ]:
print(a_torch)
a3 = a_torch.numpy().copy()
a3[0] = 999
print(a3)
print(a_torch)

tensor([777,   2,   3,   4,   5,   6])
[999   2   3   4   5   6]
tensor([777,   2,   3,   4,   5,   6])


In [ ]:
t = (1,2,3,4,5,6)

a = np.array(t)
a_tf = tf.constant(a)
a_torch = torch.tensor(a)

In [8]:
a= np.array(t) #numpy의ndarray

a_tf = tf.convert_to_tensor(a) # ndarray -> tensor (텐서플로우.텐서로 변환)
a_torch = torch.from_numpy(a) # ndarray -> tensor (토치. 넘파이에서 변환)
print(a_tf)
print(a_torch)

tf.Tensor([1 2 3 4 5 6], shape=(6,), dtype=int64)
tensor([1, 2, 3, 4, 5, 6])


In [ ]:
t = (1,2,3,4,5,6)

a_tf = tf.convert_to_tensor(a)
a_torch = torch.from_numpy(a)
print(a_tf)
print(a_torch)

tf.Tensor([1 2 3 4 5 6], shape=(6,), dtype=int64)
tensor([1, 2, 3, 4, 5, 6])


In [9]:
a = np.ones((3,3)) #모든 원소가 1로 채워진 3X3배열 생성
b = np.uint8(a)  # 배열 a를 unit8형식으로 변환
c = a.astype('float32') # qoduf a를 float32형식으로 변환
print(c)

print(id(a),a.dtype)
print(id(b),b.dtype)
print(id(c),c.dtype)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
134055927045104 float64
134055927044912 uint8
134050796008528 float32


In [10]:
a_torch = torch.rand(3,4)          #  3x4 크기의 배열을 생성하고 0과 1 사이의 임의의 값으로 채움
b_torch = a_torch.to(torch.uint8)  #  a_torch 배열을 uint8 형식으로 변환하여 b_torch에 저장
c_torch = a_torch.type(torch.float64) #  a_torch 배열을 float64 형식으로 변환하여 c_torch에 저장

print(b_torch)                      #  b_torch 배열을 출력합니다.
print(c_torch)
print(id(a_torch), a_torch.dtype)   #  a_torch 배열의 메모리 주소와 데이터 타입을 출력합니다.
print(id(b_torch), b_torch.dtype)
print(id(c_torch), c_torch.dtype)

b_torch[0,1] = 9                    #  b_torch 배열의 특정 원소를 변경
c_torch[0,0] = 1000                 #  c_torch 배열의 특정 원소를 변경
print(a_torch)
print(b_torch)
print(c_torch)

tensor([[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]], dtype=torch.uint8)
tensor([[0.1040, 0.4680, 0.2998, 0.9940],
        [0.9463, 0.7831, 0.7059, 0.3893],
        [0.1493, 0.2001, 0.1805, 0.1987]], dtype=torch.float64)
134050796174400 torch.float32
134050796174240 torch.uint8
134050796180784 torch.float64
tensor([[0.1040, 0.4680, 0.2998, 0.9940],
        [0.9463, 0.7831, 0.7059, 0.3893],
        [0.1493, 0.2001, 0.1805, 0.1987]])
tensor([[0, 9, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]], dtype=torch.uint8)
tensor([[1.0000e+03, 4.6805e-01, 2.9978e-01, 9.9401e-01],
        [9.4630e-01, 7.8312e-01, 7.0588e-01, 3.8931e-01],
        [1.4926e-01, 2.0009e-01, 1.8045e-01, 1.9871e-01]], dtype=torch.float64)


In [11]:
a_tf = tf.random.uniform(shape = (3,4))  # 3x4 크기의 텐서를 생성하고 0과 1 사이의 균등 분포에서 난수를 생성
c_tf = tf.dtypes.cast(a_tf, tf.float64)  # a_tf 텐서를 float64 형식으로 변환하여 c_tf에 저장합
print(c_tf)                              # c_tf 텐서를 출력
print(id(a_tf), a_tf.dtype)              # a_tf 텐서의 메모리 주소와 데이터 타입을 출력
print(id(c_tf), c_tf.dtype)              # c_tf 텐서의 메모리 주소와 데이터 타입을 출력


tf.Tensor(
[[0.55759323 0.4983356  0.82520878 0.27248204]
 [0.0463829  0.99655068 0.27932119 0.74602354]
 [0.32393467 0.30878186 0.96488488 0.36481023]], shape=(3, 4), dtype=float64)
134050831263248 <dtype: 'float32'>
134056489056944 <dtype: 'float64'>


In [ ]:
dir(7.0)

['__abs__',
 '__add__',
 '__bool__',
 '__ceil__',
 '__class__',
 '__delattr__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floor__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getformat__',
 '__getnewargs__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__le__',
 '__lt__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rdivmod__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rfloordiv__',
 '__rmod__',
 '__rmul__',
 '__round__',
 '__rpow__',
 '__rsub__',
 '__rtruediv__',
 '__setattr__',
 '__setformat__',
 '__sizeof__',
 '__str__',
 '__sub__',
 '__subclasshook__',
 '__truediv__',
 '__trunc__',
 'as_integer_ratio',
 'conjugate',
 'fromhex',
 'hex',
 'imag',
 'is_integer',
 'real']

In [ ]:
a_torch.dtype


torch.int64

In [ ]:
a_torch.to(dtype = torch.float32)


tensor([1., 2., 3., 4., 5., 6.])

In [ ]:
ori = [1,2,3,4]

In [ ]:
sorted(ori)

[1, 2, 3, 4]

In [ ]:
ori.sort()

In [ ]:
print(ori)

[1, 2, 3, 4]


In [ ]:
ori = [3,2,1,4]
ori.sort()

In [ ]:
ori


[1, 2, 3, 4]

#Shape 변경#


In [ ]:
a = np.arange(0,10,1) # [ s:e :step_size]
b = a.reshape((2,5))
print(a.shape,id(a))
print(b.shape,id(b))
c = np.reshape(a,(5,2))
print(c.shape,id(c))
c[0,0] = 1000
print(a)
print(b)
print(c)

(10,) 136797065283696
(2, 5) 136797065284464
(5, 2) 136797065283216
[1000    1    2    3    4    5    6    7    8    9]
[[1000    1    2    3    4]
 [   5    6    7    8    9]]
[[1000    1]
 [   2    3]
 [   4    5]
 [   6    7]
 [   8    9]]


In [ ]:
a_torch = torch.arange(0,10,1)
b_torch = a_torch.reshape((2,5))
print(a_torch.shape,id(a_torch))
print(b_torch.shape,id(b_torch))
c_torch = torch.reshape(a_torch,(5,2))
print(c_torch.shape,id(c_torch))
c_torch[0,0] = 1000

print(a_torch)
print(b_torch)
print(c_torch)


torch.Size([10]) 136797065451200
torch.Size([2, 5]) 136797065449200
torch.Size([5, 2]) 136797064975984
tensor([1000,    1,    2,    3,    4,    5,    6,    7,    8,    9])
tensor([[1000,    1,    2,    3,    4],
        [   5,    6,    7,    8,    9]])
tensor([[1000,    1],
        [   2,    3],
        [   4,    5],
        [   6,    7],
        [   8,    9]])


In [ ]:
a_tensor = tf.range(0,10,1)
b_tensor = tf.reshape(a_tensor,(2,5))
# b_tensor = a_tensor.reshape((2,5)) # not working
print(a_tensor.shape,id(a_tensor))
print(b_tensor.shape,id(b_tensor))

c_tensor = tf.reshape(a_tensor,(5,2))
print(c_tensor.shape,id(c_tensor))

# 변경하고 싶은 위치와 값을 정의
indices = tf.constant([[0, 0]]) # (2, 2) 위치를 변경하고자 함
updates = tf.constant([999]) # 해당 위치에 넣고 싶은 값

# 업데이트 적용
c_tensor = tf.tensor_scatter_nd_update(c_tensor, indices, updates)

print(a_tensor)
print(b_tensor)
print(c_tensor)

(10,) 136797068139632
(2, 5) 136797128850272
(5, 2) 136802713157872
tf.Tensor([0 1 2 3 4 5 6 7 8 9], shape=(10,), dtype=int32)
tf.Tensor(
[[0 1 2 3 4]
 [5 6 7 8 9]], shape=(2, 5), dtype=int32)
tf.Tensor(
[[999   1]
 [  2   3]
 [  4   5]
 [  6   7]
 [  8   9]], shape=(5, 2), dtype=int32)


#Slicing and Indexing

In [ ]:
a = np.arange(0,12).reshape(3,4)

print(a)
print('==================')
print(f'a[0] is "{a[0]}"')       # 첫번째 행.
print(f'a[0,2] is "{a[0,2]}"')   # 2
print(f'a[0][2] is "{a[0][2]}"') # 2
print('------------------')
print(f'a[1,2:] is "{a[1,2:]}"') # slicing의 활용.
print(f'a[1,::2] is "{a[1,::2]}"')
print(f'a[1,::-2] is "{a[1,::-2]}"')
print(f'a[1,::-1] is "{a[1,::-1]}"')
print(f'a[1,3:0:-1] is "{a[1,3:0:-1]}"')

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
a[0] is "[0 1 2 3]"
a[0,2] is "2"
a[0][2] is "2"
------------------
a[1,2:] is "[6 7]"
a[1,::2] is "[4 6]"
a[1,::-2] is "[7 5]"
a[1,::-1] is "[7 6 5 4]"
a[1,3:0:-1] is "[7 6 5]"


In [ ]:
a[0:3:-1] #코드가 돌지 않음
a[3:0:-1]

array([[ 8,  9, 10, 11],
       [ 4,  5,  6,  7]])

In [ ]:
a = np.arange(0,12).reshape(3,4)
a_torch = torch.tensor(a)

print(a_torch)
print(f'a_torch[0] is "{a_torch[0]}"')       # 첫번째 행.
print(f'a_torch[0,2] is "{a_torch[0,2]}"')   # 2
print(f'a_torch[0][2] is "{a_torch[0][2]}"') # 2

print(f'a_torch[1,2:] is "{a_torch[1,2:]}"')
print(f'a_torch[1,::2] is "{a_torch[1,::2]}"')
# print(f'a_torch[1,::-2] is "{a_torch[1,::-2]}"')
# print(f'a_torch[1,::-1] is "{a_torch[1,::-1]}"')
# print(f'a_torch[1,3:0:-1] is "{a_torch[1,3:0:-1]}"')

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
a_torch[0] is "tensor([0, 1, 2, 3])"
a_torch[0,2] is "2"
a_torch[0][2] is "2"
a_torch[1,2:] is "tensor([6, 7])"
a_torch[1,::2] is "tensor([4, 6])"


In [ ]:
i = np.where(b)
i

(array([0, 0, 0, 0, 0, 1, 1, 1, 1, 1]), array([0, 1, 2, 3, 4, 0, 1, 2, 3, 4]))

In [12]:
a = np.arange(0,12).reshape(3,4)
a_tf = tf.constant(a)

print(a_tf)
print(f'a_tf[0] is "{a_tf[0]}"')       # 첫번째 행.
print(f'a_tf[0,2] is "{a_tf[0,2]}"')   # 2
print(f'a_tf[0][2] is "{a_tf[0][2]}"') # 2

print(f'a_tf[1,2:] is "{a_tf[1,2:]}"')
print(f'a_tf[1,::2] is "{a_tf[1,::2]}"')
# print(f'a_tf[1,::-2] is "{a_tf[1,::-2]}"')
# print(f'a_tf[1,::-1] is "{a_tf[1,::-1]}"')
# print(f'a_tf[1,3:0:-1] is "{a_tf[1,3:0:-1]}"')

tf.Tensor(
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]], shape=(3, 4), dtype=int64)
a_tf[0] is "[0 1 2 3]"
a_tf[0,2] is "2"
a_tf[0][2] is "2"
a_tf[1,2:] is "[6 7]"
a_tf[1,::2] is "[4 6]"


In [13]:
x = np.array([10.,20.,30.,40.,50.])
x_torch = torch.tensor([10.,20.,30.,40.,50.])
x_tf = tf.constant([10.,20.,30.,40.,50.])

f_indices = [3, 4, 1]

print('original:')
print(x)
print('----------')
print('numpy:')
print(x[f_indices])
print('----------')
print('torch:')
print(x_torch[f_indices])
print('----------')
print('tensorflow:')
print(tf.gather(x_tf,f_indices)) #1D 에선 gahter, 2D 이상시 gather_nd
print(tf.gather_nd(x_tf, [ i for i in zip(f_indices,)])) # 굳이 쓴다면, 다음과 같이.

original:
[10. 20. 30. 40. 50.]
----------
numpy:
[40. 50. 20.]
----------
torch:
tensor([40., 50., 20.])
----------
tensorflow:
tf.Tensor([40. 50. 20.], shape=(3,), dtype=float32)
tf.Tensor([40. 50. 20.], shape=(3,), dtype=float32)


In [14]:
x = np.arange(5*5).reshape(5,5) * 10
x_torch = torch.arange(5*5).view(size=(5,5)) * 10
x_tf = tf.constant(x)

indices_0 = [0, 1, 2]
indices_1 = [0, 1, 2]

print('original:')
print(x)
print('----------')
print('numpy:')
b = x[indices_0, indices_1]
print('b.shape =',b.shape)
print(b)
print('----------')
print('torch:')
c = x_torch[indices_0, indices_1]
print('c.shape =',c.shape)
print(c)
print('----------')
print('tensorflow:')
d = tf.gather_nd(x_tf, [ i for i in zip(indices_0, indices_1)])
print('d.shape =',d.shape)
print(d)

original:
[[  0  10  20  30  40]
 [ 50  60  70  80  90]
 [100 110 120 130 140]
 [150 160 170 180 190]
 [200 210 220 230 240]]
----------
numpy:
b.shape = (3,)
[  0  60 120]
----------
torch:
c.shape = torch.Size([3])
tensor([  0,  60, 120])
----------
tensorflow:
d.shape = (3,)
tf.Tensor([  0  60 120], shape=(3,), dtype=int64)


In [15]:
x = np.arange(5*5*5).reshape(5,5,5) * 10
x_torch = torch.arange(5*5*5).view(size=(5,5,5)) * 10
x_tf = tf.constant(x)

indices_0 = [0, 1] # x
indices_1 = [1, 2] # y
indices_2 = [2, 0] # z

print('original:')
print(x)
print('----------')
print('numpy:')
b = x[indices_0, indices_1, indices_2]
print('b.shape=',b.shape)
print(b)
print('----------')
print('torch:')
c = x_torch[indices_0, indices_1, indices_2]
print('c.shape=',c.shape)
print(c)
print('----------')
print('tensorflow')
d = tf.gather_nd(x_tf, [ i for i in zip(indices_0, indices_1, indices_2)]) # multi-dim 에선 gater_nd 임.
print('d.shape=',d.shape)
print(d)

original:
[[[   0   10   20   30   40]
  [  50   60   70   80   90]
  [ 100  110  120  130  140]
  [ 150  160  170  180  190]
  [ 200  210  220  230  240]]

 [[ 250  260  270  280  290]
  [ 300  310  320  330  340]
  [ 350  360  370  380  390]
  [ 400  410  420  430  440]
  [ 450  460  470  480  490]]

 [[ 500  510  520  530  540]
  [ 550  560  570  580  590]
  [ 600  610  620  630  640]
  [ 650  660  670  680  690]
  [ 700  710  720  730  740]]

 [[ 750  760  770  780  790]
  [ 800  810  820  830  840]
  [ 850  860  870  880  890]
  [ 900  910  920  930  940]
  [ 950  960  970  980  990]]

 [[1000 1010 1020 1030 1040]
  [1050 1060 1070 1080 1090]
  [1100 1110 1120 1130 1140]
  [1150 1160 1170 1180 1190]
  [1200 1210 1220 1230 1240]]]
----------
numpy:
b.shape= (2,)
[ 70 350]
----------
torch:
c.shape= torch.Size([2])
tensor([ 70, 350])
----------
tensorflow
d.shape= (2,)
tf.Tensor([ 70 350], shape=(2,), dtype=int64)


In [16]:
x = np.arange(3*3*3).reshape(3,3,3) * 10

print('original:')
print(x)
print('----------')
print('boolean mask:')
b = x <= 270/2
print(b.shape)
print(b)
print('----------')
print('x <= 135')
print(x[b])
print('----------')
print(x[x<=270/2])
print('----------')
print('----------')
print('x <= 135 | x>= 200')
b1 = b | (x >= 200)
print('----------')
print('boolean mask')
print(b1)
print('----------')
print(x[b1])
print('----------')
print(x[ (x<=270/2) | (x>=200)])

original:
[[[  0  10  20]
  [ 30  40  50]
  [ 60  70  80]]

 [[ 90 100 110]
  [120 130 140]
  [150 160 170]]

 [[180 190 200]
  [210 220 230]
  [240 250 260]]]
----------
boolean mask:
(3, 3, 3)
[[[ True  True  True]
  [ True  True  True]
  [ True  True  True]]

 [[ True  True  True]
  [ True  True False]
  [False False False]]

 [[False False False]
  [False False False]
  [False False False]]]
----------
x <= 135
[  0  10  20  30  40  50  60  70  80  90 100 110 120 130]
----------
[  0  10  20  30  40  50  60  70  80  90 100 110 120 130]
----------
----------
x <= 135 | x>= 200
----------
boolean mask
[[[ True  True  True]
  [ True  True  True]
  [ True  True  True]]

 [[ True  True  True]
  [ True  True False]
  [False False False]]

 [[False False  True]
  [ True  True  True]
  [ True  True  True]]]
----------
[  0  10  20  30  40  50  60  70  80  90 100 110 120 130 200 210 220 230
 240 250 260]
----------
[  0  10  20  30  40  50  60  70  80  90 100 110 120 130 200 210 220 230
 24

In [17]:
x_torch = torch.arange(3*3*3).view(size=(3,3,3)) * 10
print(x_torch[ (x_torch<=270/2) | (x_torch>=200)])

print('--------------')

x_tf = tf.constant(x)
print(x_tf[ (x_tf<= tf.cast(270/2, tf.int64)) | (x_tf>=200)])

tensor([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100, 110, 120, 130,
        200, 210, 220, 230, 240, 250, 260])
--------------
tf.Tensor(
[  0  10  20  30  40  50  60  70  80  90 100 110 120 130 200 210 220 230
 240 250 260], shape=(21,), dtype=int64)


#Fancy Indexing

In [18]:
#1D Tensor 에서의 fancy Indxing
x = np.array([10.,20.,30.,40.,50.])
x_torch = torch.tensor([10.,20.,30.,40.,50.])
x_tf = tf.constant([10.,20.,30.,40.,50.])

f_indices = [3, 4, 1]
print(x[f_indices])
print(x_torch[f_indices])
print(tf.gather(x_tf,f_indices)) #1D 에선 gahter, 2D 이상시 gather_nd
print(tf.gather_nd(x_tf, [ i for i in zip(f_indices,)])) # 굳이 쓴다면, 다음과 같이.

[40. 50. 20.]
tensor([40., 50., 20.])
tf.Tensor([40. 50. 20.], shape=(3,), dtype=float32)
tf.Tensor([40. 50. 20.], shape=(3,), dtype=float32)


2D Tensor에서의 Fancy Indexing

In [ ]:
x = np.arange(5*5).reshape(5,5) * 10
x_torch = torch.arange(5*5).view(size=(5,5)) * 10
x_tf = tf.constant(x)

indices_0 = [0, 1, 2]
indices_1 = [0, 1, 2]


b = x[indices_0, indices_1]
print(b.shape)
print(b)
print('----------')
c = x_torch[indices_0, indices_1]
print(c.shape)
print(c)
print('----------')
d = tf.gather_nd(x_tf, [ i for i in zip(indices_0, indices_1)])
print(d.shape)
print(d)


3D Tensor Example

In [19]:
x = np.arange(5*5*5).reshape(5,5,5) * 10
x_torch = torch.arange(5*5*5).view(size=(5,5,5)) * 10
x_tf = tf.constant(x)

indices_0 = [0, 1]
indices_1 = [1, 2]
indices_2 = [2, 0]

b = x[indices_0, indices_1, indices_2]
print(b.shape)
print(b)
print('----------')
c = x_torch[indices_0, indices_1, indices_2]
print(c.shape)
print(c)
print('----------')
d = tf.gather_nd(x_tf, [ i for i in zip(indices_0, indices_1, indices_2)]) # multi-dim 에선 gater_nd 임.
print(d.shape)
print(d)

(2,)
[ 70 350]
----------
torch.Size([2])
tensor([ 70, 350])
----------
(2,)
tf.Tensor([ 70 350], shape=(2,), dtype=int64)



Boolean Mask

In [20]:
x = np.arange(3*3*3).reshape(3,3,3) * 10

b = x <= 270/2
print(b.shape)
print(b)
print('----------')
print(x[b])
print('----------')
print(x[x<=270/2])

b1 = b | (x >= 200)
print('----------')
print(b1)
print('----------')
print(x[b1])
print('----------')
print(x[ (x<=270/2) | (x>=200)])

(3, 3, 3)
[[[ True  True  True]
  [ True  True  True]
  [ True  True  True]]

 [[ True  True  True]
  [ True  True False]
  [False False False]]

 [[False False False]
  [False False False]
  [False False False]]]
----------
[  0  10  20  30  40  50  60  70  80  90 100 110 120 130]
----------
[  0  10  20  30  40  50  60  70  80  90 100 110 120 130]
----------
[[[ True  True  True]
  [ True  True  True]
  [ True  True  True]]

 [[ True  True  True]
  [ True  True False]
  [False False False]]

 [[False False  True]
  [ True  True  True]
  [ True  True  True]]]
----------
[  0  10  20  30  40  50  60  70  80  90 100 110 120 130 200 210 220 230
 240 250 260]
----------
[  0  10  20  30  40  50  60  70  80  90 100 110 120 130 200 210 220 230
 240 250 260]


In [44]:
x_torch = torch.arange(3*3*3).view(size=(3,3,3)) * 10

print(x_torch[ (x_torch<=270/2) | (x_torch>=200)])

tensor([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100, 110, 120, 130,
        200, 210, 220, 230, 240, 250, 260])


In [45]:
x_tf = tf.constant(x)

print(x_tf[ (x_tf<= tf.cast(270/2, tf.int64)) | (x_tf>=200)])

InvalidArgumentError: cannot compute LessEqual as input #1(zero-based) was expected to be a double tensor but is a int64 tensor [Op:LessEqual] name: 


combined indexing

In [22]:
import numpy as np

x = np.array([0,1,2,3,4,5,6,7,8]).reshape((3,3))
print(x.shape)

mask = np.array([True, False, True])
cidx = np.array([2,0,1])
print(mask.shape)
print(cidx.shape)

print('--------')
print(x)
print('--------')
print(x[mask,cidx[:,np.newaxis]]) # broadcasting 으로 fancyindexing 이 이루어짐.

(3, 3)
(3,)
(3,)
--------
[[0 1 2]
 [3 4 5]
 [6 7 8]]
--------
[[2 8]
 [0 6]
 [1 7]]


In [23]:
import torch

x_torch = torch.tensor([0,1,2,3,4,5,6,7,8]).reshape((3,3))
if torch.cuda.is_available():
    x_torch = x_torch.to("cuda")

x_torch[mask,cidx[:,np.newaxis]]

tensor([[2, 8],
        [0, 6],
        [1, 7]])

In [24]:
a = np.array([1,0,1])
b = cidx[:,np.newaxis]
a*b

array([[2, 0, 2],
       [0, 0, 0],
       [1, 0, 1]])

In [25]:
x = np.array([0,1,2,3,4,5,6,7,8]).reshape((3,3))

# booelan mask 대신, 일반적인 수치로도 가능.
r = x[[0,2],cidx[:,np.newaxis]] # combined indexing의 경우, ₩내부에서 broadcasting 룰이 적용됨.

print(x)
print('--------')
print(r)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
--------
[[2 8]
 [0 6]
 [1 7]]


In [ ]:
import numpy as np

x = np.array([0,1,2,3,4,5,6,7]).reshape(2,2,2)
t = np.array([0,1])
r = x[[False,True],t[np.newaxis,:]]
print(x.shape)
print(x)
print('--------')
print(r.shape)
print(r)
print('--------')
print(t[np.newaxis, :].shape)
print(t[np.newaxis, :])

fancy indexing을 활용한 처리.

In [32]:
x = np.arange(10).reshape(1,10)
print('before:',x)
r_idx = np.array([0])
c_idx = np.array([9, 1, 3, 9]) # 중복되어도 더해지진 않음.
x[r_idx,c_idx] = x[r_idx,c_idx] +10
print('after :',x)

before: [[0 1 2 3 4 5 6 7 8 9]]
after : [[ 0 11  2 13  4  5  6  7  8 19]]


In [33]:
x = np.arange(10)
print('before:',x)
np.add.at(x,i,10) # 중복된 index를 더해줌.
print('after :',x)


before: [0 1 2 3 4 5 6 7 8 9]
after : [ 0 11  2 13  4  5  6  7  8 29]


In [38]:
x_torch = torch.arange(10)
print(x_torch.dtype)
print('before:',x_torch)
i = torch.tensor([9, 1, 3, 9]) # 중복되어도 더해지진 않음.
x_torch[i] = x_torch[i] +10
print('after :',x_torch)

torch.int64
before: tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
after : tensor([ 0, 11,  2, 13,  4,  5,  6,  7,  8, 19])


In [41]:
import numpy as np

rng = np.random.default_rng(1)
x = rng.random((5,2))
print(x)

[[0.51182162 0.9504637 ]
 [0.14415961 0.94864945]
 [0.31183145 0.42332645]
 [0.82770259 0.40919914]
 [0.54959369 0.02755911]]


In [42]:
y0 = x[:, np.newaxis]
.shape

SyntaxError: invalid syntax (<ipython-input-42-4ecc719f291e>, line 2)