<a href="https://colab.research.google.com/github/Hyebeen-101903/AI_Programing/blob/main/%EC%9D%B8%EC%A7%80%ED%94%84_11%EC%A3%BC%EC%B0%A8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
from torch import nn
from torch.nn import init
from collections import OrderedDict

In [2]:
class SimpleModel0(nn.Module):

  def __init__(self, n_in_f, n_out_f):

    super().__init__()

    self.l0 = nn.Linear(n_in_f, n_out_f)

    const_weight = 1.
    const_bias = 0.5

    init.constant_(self.l0.weight, const_weight)
    if self.l0.bias is not None:
      init.constant_(self.l0.bias, const_bias)

  def forward(self, x):
    return self.l0(x)

In [3]:
class SimpleModel1(nn.Module):

  def __init__(self, n_in_f, n_out_f):

    super().__init__()

    self.l0 = nn.Linear(n_in_f, n_out_f)
    self.l1 = nn.Linear(n_out_f, n_out_f)

    const_weight = 2.
    const_bias = 1.5

    init.constant_(self.l0.weight, const_weight)
    if self.l0.bias is not None:
      init.constant_(self.l0.bias, const_bias)

  def forward(self, x):
    return self.l0(x)

In [4]:
model = SimpleModel0(3,1)

print(list(model.named_parameters()))

[('l0.weight', Parameter containing:
tensor([[1., 1., 1.]], requires_grad=True)), ('l0.bias', Parameter containing:
tensor([0.5000], requires_grad=True))]


In [6]:
ordered_dict_params = model.state_dict()
for c in ordered_dict_params.items():
  print(f'{c[0]:<10}={c[1]}')

l0.weight =tensor([[1., 1., 1.]])
l0.bias   =tensor([0.5000])


In [7]:
torch.save(model.state_dict(), 'model_params.pth')

In [11]:
n_model = SimpleModel1(3,1)

for old, new in zip(model.parameters(), n_model.parameters()):

  if not torch.equal(old,new):
    print('model and n_model w/ default init do not have parameters with the same values!')
    break
else:
  print('model and n_model w/ default init have parameters with the same values!')

model and n_model w/ default init do not have parameters with the same values!


In [10]:
for old, new in zip(model.parameters(), n_model.parameters()):

  if not torch.equal(old,new):
    print('model and n_model do not have parameters with the same values!')
    break
else:
  print('model and n_model have parameters with the same values!')

model and n_model have parameters with the same values!


In [13]:
model = SimpleModel0(3,1)

In [14]:
torch.save(model,'model.pth')

In [15]:
class SimpleModel0(nn.Module):

  def __init__(self, n_in_f, n_out_f):

    super().__init__()

    self.l0 = nn.Linear(n_in_f, n_out_f)

    const_weight = 2.
    const_bias = 1.5

    init.constant_(self.l0.weight, const_weight)
    if self.l0.bias is not None:
      init.constant_(self.l0.bias, const_bias)

  def forward(self, x):
    return self.l0(x)

In [16]:
n_model = torch.load('model.pth')
print(f'{type(n_model)=}, {n_model}')


type(n_model)=<class '__main__.SimpleModel0'>, SimpleModel0(
  (l0): Linear(in_features=3, out_features=1, bias=True)
)


In [17]:
for c in n_model.named_parameters():
  print(c)

('l0.weight', Parameter containing:
tensor([[1., 1., 1.]], requires_grad=True))
('l0.bias', Parameter containing:
tensor([0.5000], requires_grad=True))


In [18]:
import pickle

pickle.dump(n_model,open('m.pkl','wb'))
nn_model = pickle.load(open('m.pkl','rb'))
nn_model

SimpleModel0(
  (l0): Linear(in_features=3, out_features=1, bias=True)
)

In [19]:
for old, new in zip(n_model.parameters(), nn_model.parameters()):

  if not torch.equal(old,new):
    print('model and n_model do not have parameters with the same values!')
    break
else:
  print('model and n_model have parameters with the same values!')

model and n_model have parameters with the same values!


In [20]:
import torch
import torch.nn as nn
from collections import OrderedDict

# 간단한 모델 정의
class MyModel(nn.Module):
    def __init__(self):
        super(MyModel, self).__init__()
        self.linear = nn.Linear(10, 5)
        self.bn = nn.BatchNorm1d(5)
        # self.sub = nn.Sequential(
        #     OrderedDict({
        #         'ds00_layer': nn.Linear(5,5),
        #         'ds00_bn':nn.BatchNorm1d(5),
        #         'ds00_act': nn.ReLU(),
        #         'ds01_layer': nn.Linear(5,5),
        #     })
        # )

    def forward(self, x):
        x = self.linear(x)
        x = self.bn(x)
        x = self.sub(x)
        return x

# 모델 인스턴스 생성
model = MyModel()

# 모델의 state_dict 가져오기
state_dict = model.state_dict()

# state_dict 내용 출력
for key, value in state_dict.items():
    print(f"{key:<25}: {str(type(value)):<20}: {value.shape}")

linear.weight            : <class 'torch.Tensor'>: torch.Size([5, 10])
linear.bias              : <class 'torch.Tensor'>: torch.Size([5])
bn.weight                : <class 'torch.Tensor'>: torch.Size([5])
bn.bias                  : <class 'torch.Tensor'>: torch.Size([5])
bn.running_mean          : <class 'torch.Tensor'>: torch.Size([5])
bn.running_var           : <class 'torch.Tensor'>: torch.Size([5])
bn.num_batches_tracked   : <class 'torch.Tensor'>: torch.Size([])


In [21]:
# 모델의 state_dict 가져오기
state_dict0 = model.state_dict(prefix='ds', keep_vars=True)

# state_dict 내용 출력
for key, value in state_dict0.items():
    print(f"{key:<25}: {str(type(value)):<20}: {value.shape}")

dslinear.weight          : <class 'torch.nn.parameter.Parameter'>: torch.Size([5, 10])
dslinear.bias            : <class 'torch.nn.parameter.Parameter'>: torch.Size([5])
dsbn.weight              : <class 'torch.nn.parameter.Parameter'>: torch.Size([5])
dsbn.bias                : <class 'torch.nn.parameter.Parameter'>: torch.Size([5])
dsbn.running_mean        : <class 'torch.Tensor'>: torch.Size([5])
dsbn.running_var         : <class 'torch.Tensor'>: torch.Size([5])
dsbn.num_batches_tracked : <class 'torch.Tensor'>: torch.Size([])
