<a href="https://colab.research.google.com/github/Hyebeen-101903/AI_Programing/blob/main/%EC%9D%B8%EC%A7%80%ED%94%84_4%EC%A3%BC%EC%B0%A8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import tensorflow as tf
import torch

In [ ]:
np.__version__

'1.25.2'

In [ ]:
tf.__version__

'2.15.0'

In [ ]:
torch.__version__

'2.2.1+cu121'

In [ ]:
a = np.random.rand(2, 3)
t1 = np.transpose(a)
# t1 = np.transpose(a, (1, 0))
t2 = a.T
print(a.shape)
print(t1.shape)
print(t2.shape)

t2[0,1] = 77
print(a[1,0])
print(t1[0,1])
print(t2[0,1])


(2, 3)
(3, 2)
(3, 2)
77.0
77.0
77.0


In [ ]:
a_torch = torch.rand(2, 3)
t1_torch = torch.transpose(a_torch, 0, 1)
t2_torch = a_torch.T
print(a_torch.shape)
print(t1_torch.shape)
print(t2_torch.shape)

t2_torch[0,1] = 77
print(a_torch[1,0])
print(t1_torch[0,1])
print(t2_torch[0,1])

torch.Size([2, 3])
torch.Size([3, 2])
torch.Size([3, 2])
tensor(77.)
tensor(77.)
tensor(77.)


In [ ]:
a_tf = tf.random.normal([2, 3])
t1_tf = tf.transpose(a_tf)
t2_tf = tf.transpose(a_tf, perm=[1, 0])
print(a_tf.shape, a_tf.dtype)
print(t1_tf.shape, t1_tf.dtype)
print(t2_tf.shape, t2_tf.dtype)

indices = tf.constant([[0, 1]]) # (2, 2) 위치를 변경하고자 함
updates = tf.constant([77], dtype=tf.float32) # 해당 위치에 넣고 싶은 값
t2_tf = tf.tensor_scatter_nd_update(t2_tf, indices, updates)
print(a_tf[1,0])
print(t1_tf[0,1])
print(t2_tf[0,1])

(2, 3) <dtype: 'float32'>
(3, 2) <dtype: 'float32'>
(3, 2) <dtype: 'float32'>
tf.Tensor(-0.5324527, shape=(), dtype=float32)
tf.Tensor(-0.5324527, shape=(), dtype=float32)
tf.Tensor(77.0, shape=(), dtype=float32)


In [ ]:
a = np.random.rand(2, 3, 4)
t1 = np.transpose(a, (0, 2, 1))
print(a.shape)
print(t1.shape)
t1[0,1,2] = 77
print(a[0,2,1])
print(t1[0,1,2])

In [ ]:
a_torch = torch.rand(2, 3, 4)
t1_torch = torch.permute(a_torch, (0, 2, 1))
print(a_torch.shape)
print(t1_torch.shape)
t1_torch[0,1,2] = 77
print(a_torch[0,2,1])
print(t1_torch[0,1,2])

torch.Size([2, 3, 4])
torch.Size([2, 4, 3])
tensor(77.)
tensor(77.)


In [ ]:
a_tf = tf.random.normal([2, 3, 4])
t1_tf = tf.transpose(a_tf, perm=[0, 2, 1])
print(a_tf.shape, a_tf.dtype)
print(t1_tf.shape, t1_tf.dtype)

(2, 3, 4) <dtype: 'float32'>
(2, 4, 3) <dtype: 'float32'>


In [ ]:
import sys
print(sys.version)

3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]


# libary 설치 여부 및 colab 동작 여부 **확인**

In [ ]:
import importlib
# Check if a module exists
try:
  module_name = "google.colab"
  if importlib.util.find_spec(module_name):
    print(f"{module_name} module exists.")
  else:
    print(f"{module_name} module does not exist.")
except ImportError:
  print(f"{module_name} module does not exist.")

# Check module location
try:
  module_spec = importlib.util.find_spec("torch")
  if module_spec:
    print(f"{module_spec.name} module is located at {module_spec.origin}.")
except ImportError:
  print(f"{module_name} module does not exist.")

google.colab module exists.
torch module is located at /usr/local/lib/python3.10/dist-packages/torch/__init__.py.


In [ ]:
try:
    metadata = importlib.metadata.PackagePath(module_name)
    print(f"{module_name} 패키지가 존재합니다.")
    print(f"패키지 이름: {metadata.name}")
    print(f"패키지 버전: {metadata.locate}")
    print(f"패키지 버전: {importlib.metadata.version(module_name)}")

except importlib.metadata.PackageNotFoundError:
    print(f"{module_name} 패키지가 존재하지 않습니다.")

google.colab 패키지가 존재합니다.
패키지 이름: google.colab
패키지 버전: <bound method PackagePath.locate of PackagePath('google.colab')>
패키지 버전: 1.0.0


# **Tensor 생성**

In [ ]:
t = (1,2,3,4,5,6)
a = np.array(t)
print(type(t))
print(type(a))

<class 'tuple'>
<class 'numpy.ndarray'>


In [ ]:
print(a.ndim)
print(a.shape)
print(a.itemsize) #bytes
print(a.size)
print(a.dtype)

1
(6,)
8
6
int64


In [ ]:

a = np.array([1.,2.,3.])
print(a.dtype)
a = np.array([1.,2.,3.], dtype=int)
print(a.dtype)
a = np.array([1.,2.,3.], dtype=float)
print(a.dtype)

float64
int64
float64


# **tensorflow에서의 tensor 생성**

In [ ]:
tensor = tf.constant(t)
print(tf.rank(tensor))
print(tensor.ndim)
print(tensor.shape)
# print(tensor.itemsize)  #error. not supported
# print(tensor.size)      #error. not supported
print(tensor.dtype)
tensor

tf.Tensor(1, shape=(), dtype=int32)
1
(6,)
<dtype: 'int32'>


<tf.Tensor: shape=(6,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6], dtype=int32)>

# **pytorch에서의 tensor 생성**

In [ ]:
p = torch.tensor(t)
print(p.ndim)
print(p.shape)
print(p.itemsize)
print(p.size())    # not attribute but method
print(p.dtype)

1
torch.Size([6])
8
torch.Size([6])
torch.int64


# **기본 type**

In [ ]:
print(np.array([1.,2.,3.]).dtype)
print(np.array([1,2,3]).dtype)
print(tf.constant([1.,2.,3.]).dtype)
print(tf.constant([1,2,3]).dtype)
print(torch.tensor([1.,2.,3.]).dtype)
print(torch.tensor([1,2,3]).dtype)

float64
int64
<dtype: 'float32'>
<dtype: 'int32'>
torch.float32
torch.int64


In [ ]:
# nested lists result in multi-dimensional arrays
a = np.array([range(i, i + 3) for i in [2, 4, 6]])
print(a.ndim)
print(a.shape)
print(a.itemsize) #bytes
print(a.size)
print(a.dtype)
a

2
(3, 3)
8
9
int64


array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [ ]:
tensor = tf.constant(a)
print(tf.rank(tensor))
print(tensor.ndim)
# print(tensor.itemsize)  #error. not supported
# print(tensor.size)      #error. not supported
print(tensor.dtype)
tensor

tf.Tensor(2, shape=(), dtype=int32)
2
<dtype: 'int64'>


<tf.Tensor: shape=(3, 3), dtype=int64, numpy=
array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])>

In [ ]:
p = torch.tensor(a)
print(p.ndim)
print(p.shape)
print(p.itemsize)
print(p.size())    # not attribute but method
print(p.dtype)
p

2
torch.Size([3, 3])
8
torch.Size([3, 3])
torch.int64


tensor([[2, 3, 4],
        [4, 5, 6],
        [6, 7, 8]])

# **tensor를 특정 값으로 초기화**

In [ ]:
a = np.zeros((3,2)) # default dtype = float64
# a = np.zeros(shape=(4,4),dtype=np.uint8)
print(a.dtype)
a

float64


array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [ ]:
a_tf = tf.zeros(shape=(3,2)) #default dtype = float32
print(a_tf.dtype)
a_tf
# a_tf.numpy()

<dtype: 'float32'>


<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[0., 0.],
       [0., 0.],
       [0., 0.]], dtype=float32)>

In [ ]:
a_tf.numpy() # 다시 numpy array로

array([[0., 0.],
       [0., 0.],
       [0., 0.]], dtype=float32)

In [ ]:
p = torch.zeros(size=(3,2)) # shape 대신에 size
print(p.dtype)
p

torch.float32


tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [ ]:
a = np.ones((4,2,3))
print(a.dtype)
a


float64


array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [ ]:
a_tf = tf.ones(shape=(4,2,3))
# a_tf = tf.ones((4,2), dtype=tf.int64)
print(a_tf.dtype)
a_tf


<dtype: 'float32'>


<tf.Tensor: shape=(4, 2, 3), dtype=float32, numpy=
array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]], dtype=float32)>

# **난수로 구성된 tensor 생성**

In [ ]:
A = np.random.rand(3,4)
print(A.dtype)
A

float64


array([[0.47057355, 0.68811627, 0.03306503, 0.3828621 ],
       [0.9627153 , 0.85439347, 0.64349523, 0.53254583],
       [0.95818278, 0.65172976, 0.73294893, 0.3267134 ]])

In [ ]:
A_tf = tf.random.uniform(shape=(3,4), minval=0., maxval=1. )
A_tf

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0.6411561 , 0.8348224 , 0.19180155, 0.06217623],
       [0.83678806, 0.4358847 , 0.7759253 , 0.08593047],
       [0.29950535, 0.96230674, 0.88044226, 0.3833257 ]], dtype=float32)>

In [ ]:
A_torch = torch.rand(3,4)
print(A_torch.dtype)
A_torch

torch.float32


tensor([[0.1618, 0.8951, 0.4060, 0.2244],
        [0.5173, 0.1691, 0.3552, 0.8777],
        [0.0411, 0.0550, 0.4997, 0.5200]])

In [ ]:
A = np.random.randn(3,4) #normal distribution of which parameters are mean and standard deviation.
print(A.shape)
print(np.mean(A),np.std(A))
A

(3, 4)
0.042196259623932454 1.175503905597633


array([[ 0.54798653, -2.06628628,  1.32741968,  0.25848843],
       [-1.51369878, -0.56778046,  0.83602593,  1.34208834],
       [-1.49217053, -0.3335801 ,  0.63508231,  1.53278006]])

In [ ]:
A_tf = tf.random.normal(shape=(3,4),mean=0., stddev=1.0)
print(A_tf.shape)
print(tf.math.reduce_mean(A_tf),tf.math.reduce_std(A_tf))
A_tf

(3, 4)
tf.Tensor(-0.1505007, shape=(), dtype=float32) tf.Tensor(0.91605973, shape=(), dtype=float32)


<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[ 0.66031677, -0.16029674,  1.9151546 , -0.4188731 ],
       [-1.0227128 , -0.8565724 , -0.8215166 , -1.7473283 ],
       [-0.26828077,  0.5717319 ,  0.36044988, -0.01808099]],
      dtype=float32)>

# **indexing & slicing on Tensor**

In [ ]:
A = np.arange(0,12).reshape(3,4)
print(A.dtype)
A

int64


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
# A_tf = tf.constant(tf.range(0,12),shape=(3,4))
A_tf = tf.Variable(np.arange(0,12).reshape(3,4), dtype=tf.int32)
print(A_tf.dtype)
A_tf

<dtype: 'int32'>


<tf.Variable 'Variable:0' shape=(3, 4) dtype=int32, numpy=
array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]], dtype=int32)>

In [ ]:
A_torch = torch.tensor(torch.arange(0,12).reshape(3,4))
print(A_torch.dtype)
A_torch

torch.int64


<ipython-input-33-5e1d184cde73>:1: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  A_torch = torch.tensor(torch.arange(0,12).reshape(3,4))


tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [ ]:
print(A)
print(f'A[0] is "{A[0]}"')
print(f'A[0,2] is "{A[0,2]}"')
print(f'A[0][2] is "{A[0][2]}"')

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
A[0] is "[0 1 2 3]"
A[0,2] is "2"
A[0][2] is "2"


In [ ]:
A[2,2]

10

In [ ]:
A[2,2] = 77
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 77, 11]])

In [ ]:
print(A)
print(f'A[1,2:] is "{A[1,2:]}"')
print(f'A[1,::2] is "{A[1,::2]}"')
print(f'A[1,::-2] is "{A[1,::-2]}"')
print(f'A[1,::-1] is "{A[1,::-1]}"')
print(f'A[1,3:0:-1] is "{A[1,3:0:-1]}"')

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 77 11]]
A[1,2:] is "[6 7]"
A[1,::2] is "[4 6]"
A[1,::-2] is "[7 5]"
A[1,::-1] is "[7 6 5 4]"
A[1,3:0:-1] is "[7 6 5]"


In [ ]:
print(A)
A[1:3,1:3] = 3*A[1:3,1:3]
A

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 77 11]]


array([[  0,   1,   2,   3],
       [  4,  15,  18,   7],
       [  8,  27, 231,  11]])

In [ ]:
A[1:3,1:3] = 777
A

array([[  0,   1,   2,   3],
       [  4, 777, 777,   7],
       [  8, 777, 777,  11]])

In [ ]:
print(A_tf)
print(f'A_tf[1,2:] is "{A_tf[1,2:]}"')
print(f'A_tf[1,::2] is "{A_tf[1,::2]}"')
print(f'A_tf[1,::-2] is "{A_tf[1,::-2]}"')
print(f'A_tf[1,::-1] is "{A_tf[1,::-1]}"')
print(f'A_tf[1,3:0:-1] is "{A_tf[1,3:0:-1]}"')

<tf.Variable 'Variable:0' shape=(3, 4) dtype=int32, numpy=
array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]], dtype=int32)>
A_tf[1,2:] is "[6 7]"
A_tf[1,::2] is "[4 6]"
A_tf[1,::-2] is "[7 5]"
A_tf[1,::-1] is "[7 6 5 4]"
A_tf[1,3:0:-1] is "[7 6 5]"


In [ ]:
print(A_torch)
print(f'A[1,2:] is "{A_torch[1,2:]}"')
print(f'A[1,::2] is "{A_torch[1,::2]}"')
# print(f'A[1,::-2] is "{A_torch[1,::-2]}"') # not working. positive step 만 지원.
# print(f'A[1,::-1] is "{A_torch[1,::-1]}"') # not working. positive step 만 지원.
# print(f'A[1,3:0:-1] is "{A_torch[1,3:0:-1]}"') # not working. positive step 만 지원.

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
A[1,2:] is "tensor([6, 7])"
A[1,::2] is "tensor([4, 6])"


In [ ]:
a_torch = torch.rand(5,5)
b_torch = a_torch[1:3,1:3]          # view
# b_torch = a_torch[1:3,1:3].copy()
b_torch[:] = 3.

print(a_torch)
print(b_torch)

tensor([[0.5807, 0.3211, 0.3507, 0.5799, 0.9500],
        [0.0737, 3.0000, 3.0000, 0.7296, 0.5372],
        [0.3892, 3.0000, 3.0000, 0.8810, 0.0656],
        [0.3608, 0.6801, 0.5623, 0.8912, 0.1820],
        [0.2189, 0.8461, 0.9622, 0.1527, 0.6763]])
tensor([[3., 3.],
        [3., 3.]])


# **tensor의 dtype 변경**

In [ ]:
a = np.ones((3,3))
c = a.astype('float32')
print(c)

print(id(a),a.dtype)
print(id(c),c.dtype)


[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
138032996120112 float64
138032996565136 float32


In [ ]:
a.astype(np.float128)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float128)

In [ ]:
c = np.uint8(a)
print(c)

print(id(a),a.dtype)
print(id(c),c.dtype)

[[1 1 1]
 [1 1 1]
 [1 1 1]]
138032996120112 float64
138032996118864 uint8


In [ ]:
a_tf = tf.random.uniform(shape=(3,4))
print(a_tf.dtype)
c_tf = tf.dtypes.cast(a_tf,tf.float64)
print(c_tf.dtype)
c_tf

<dtype: 'float32'>
<dtype: 'float64'>


<tf.Tensor: shape=(3, 4), dtype=float64, numpy=
array([[0.32832778, 0.47895086, 0.48024452, 0.76181209],
       [0.25890362, 0.23382413, 0.85778439, 0.7859627 ],
       [0.81595469, 0.08758891, 0.31528056, 0.5594877 ]])>

In [ ]:
a_torch = torch.rand(3,4)
print(a_torch.dtype, id(a_torch))
c_torch = a_torch.type(torch.float64)
print(c_torch.dtype, id(c_torch))
c_torch

torch.float32 138032996402736
torch.float64 138032996730736


tensor([[0.0843, 0.0672, 0.8297, 0.7233],
        [0.3020, 0.3153, 0.3918, 0.2224],
        [0.4414, 0.7522, 0.7381, 0.7474]], dtype=torch.float64)

In [ ]:

import torch

a = torch.tensor([ range(i,i+3) for i in [0,3,6]])
a

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [ ]:
a.storage()
# a.untyped_storage()

<ipython-input-49-07cd75b5fe08>:1: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  a.storage()


 0
 1
 2
 3
 4
 5
 6
 7
 8
[torch.storage.TypedStorage(dtype=torch.int64, device=cpu) of size 9]

In [ ]:
a.is_contiguous()

True

In [ ]:
a_sub = a[1:,0]
print(a_sub)

tensor([3, 6])


In [ ]:
print(a_sub.storage())
a_sub.is_contiguous()

 0
 1
 2
 3
 4
 5
 6
 7
 8
[torch.storage.TypedStorage(dtype=torch.int64, device=cpu) of size 9]


False

In [ ]:
a.storage().data_ptr() == a_sub.storage().data_ptr()

True

In [ ]:
a_t = torch.transpose(a,0,1)
a_t

tensor([[0, 3, 6],
        [1, 4, 7],
        [2, 5, 8]])

In [ ]:
print(a_t.storage())
a_t.is_contiguous()


 0
 1
 2
 3
 4
 5
 6
 7
 8
[torch.storage.TypedStorage(dtype=torch.int64, device=cpu) of size 9]


False

In [ ]:
a_t[0,1] = 999
print(a_t)
print('-------')
print(a)
print('-------')
print(a_sub)

tensor([[  0, 999,   6],
        [  1,   4,   7],
        [  2,   5,   8]])
-------
tensor([[  0,   1,   2],
        [999,   4,   5],
        [  6,   7,   8]])
-------
tensor([999,   6])


In [ ]:
print(f"{a.shape=}, {a.size()=}, {a.stride()=}, {a.storage_offset()=}")
print(f"{a_t.shape=}, {a_t.size()=}, {a_t.stride()=}, {a_t.storage_offset()=}")
print(f"{a_sub.shape=}, {a_sub.size()=}, {a_sub.stride()=}, {a_sub.storage_offset()=}")

a.shape=torch.Size([3, 3]), a.size()=torch.Size([3, 3]), a.stride()=(3, 1), a.storage_offset()=0
a_t.shape=torch.Size([3, 3]), a_t.size()=torch.Size([3, 3]), a_t.stride()=(1, 3), a_t.storage_offset()=0
a_sub.shape=torch.Size([2]), a_sub.size()=torch.Size([2]), a_sub.stride()=(3,), a_sub.storage_offset()=3


In [ ]:
a_v = a.view((9,))
a_v

tensor([  0,   1,   2, 999,   4,   5,   6,   7,   8])

In [ ]:
a_r = a.reshape((9,))
a_r[3] = 777
print('데이터 저장공간을 share함.')
print('a_r: af.reshape')
print(a_r)
print('a: orginal')
print(a)
print('a_t: transposed')
print(a_t)

데이터 저장공간을 share함.
a_r: af.reshape
tensor([  0,   1,   2, 777,   4,   5,   6,   7,   8])
a: orginal
tensor([[  0,   1,   2],
        [777,   4,   5],
        [  6,   7,   8]])
a_t: transposed
tensor([[  0, 777,   6],
        [  1,   4,   7],
        [  2,   5,   8]])


In [ ]:
a_t_r = a_t.reshape((9,)) # uncontiguous tensor에서는 새로 생성이 이루어짐.
a_t_r

tensor([  0, 777,   6,   1,   4,   7,   2,   5,   8])

In [ ]:
a_t_r[1] = 999
print(a_t_r)
print(a_t) # 달라짐.

tensor([  0, 999,   6,   1,   4,   7,   2,   5,   8])
tensor([[  0, 777,   6],
        [  1,   4,   7],
        [  2,   5,   8]])


In [ ]:
act = a_t.contiguous()
act

tensor([[  0, 777,   6],
        [  1,   4,   7],
        [  2,   5,   8]])

In [ ]:
act.storage()

 0
 777
 6
 1
 4
 7
 2
 5
 8
[torch.storage.TypedStorage(dtype=torch.int64, device=cpu) of size 9]

In [ ]:
act[1] = 999
print(act)
print(a_t)

tensor([[  0, 777,   6],
        [999, 999, 999],
        [  2,   5,   8]])
tensor([[  0, 777,   6],
        [  1,   4,   7],
        [  2,   5,   8]])


In [ ]:
print(a)
print('------')
print('permute axis-0 and axis-1 = transpose')
ap = a.permute([1,0]) # permute axis-0 and axis-1
ap

tensor([[  0,   1,   2],
        [777,   4,   5],
        [  6,   7,   8]])
------
permute axis-0 and axis-1 = transpose


tensor([[  0, 777,   6],
        [  1,   4,   7],
        [  2,   5,   8]])

In [ ]:
a.storage().data_ptr() == ap.storage().data_ptr()

True

In [ ]:
print(ap.is_contiguous())

False


In [ ]:
ap2 = ap.contiguous()
a.storage().data_ptr() == ap2.storage().data_ptr()

False

In [ ]:
ap2.is_contiguous()

True