<a href="https://colab.research.google.com/github/Hyebeen-101903/AI_Programing/blob/main/%EC%9D%B8%EC%A7%80%ED%94%84_2%EC%A3%BC%EC%B0%A8_%EC%88%98%EC%97%85%EB%82%B4%EC%9A%A9_numpy01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount("/content/drive")

Mounted at /content/drive


In [ ]:
import numpy as np
import tensorflow as tf
import torch


In [ ]:
np.__version__


'1.25.2'

In [ ]:
tf.__version__

'2.15.0'

In [ ]:
torch.__version__

'2.3.0+cu121'

In [ ]:
import sys
print(sys.version)

3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]


#Tensor 생성하기#

np.array ( list [,dtype])

list 나 tuple 등으로 ndarray 생성.
dtype : data type of element.
- float64 : default type in the numpy.
- uint8 : unsigned int (8bit), the most commonly used for image processing
- int8 : signed int (8bit)
- float32 : float (32bit)

In [ ]:
t = (1,2,3,4,5,6)
a = np.array(t) # Numpy 배열을 생성
a_tf = tf.constant(a) #TensorFlow 상수 생성 (numpy의 array를 tf로 타입 변환)
a_torch = torch.tensor(a)  #Pytorch 텐서 생성

print(type(t))
print(type(a))
print(type(a_tf))
print(type(a_torch))

<class 'tuple'>
<class 'numpy.ndarray'>
<class 'tensorflow.python.framework.ops.EagerTensor'>
<class 'torch.Tensor'>


In [ ]:
print(a.ndim) #배열의 차원 수
print(a.shape) # 각 차원의 크기
print(a.itemsize)  #배열의 각 요소의 bytes 크기를 반환
print(a.size) # 배열의 모든 요소의 총 개수 반환
print(a.dtype) # 배열 요소의 데이터 타입 반환

1
(6,)
8
6
int64


In [ ]:
a = np.array([1.,2.,3.])
print(a.dtype)

a = np.array([1.,2.,3.], dtype=int) # float 타입의 숫자를 int 타입으로 변환하여 배열을 생성
print(a.dtype)

a = np.array([1.,2.,3.], dtype=float)
print(a.dtype)


float64
int64
float64


In [ ]:
t = (1, 2, 3,4,5,6)
tensor = tf.constant(t)
print(tf.rank(tensor))
print(tensor.ndim)
print(tensor.shape)
# print(tensor.itemsize)  #error. not supported
# print(tensor.size)      #error. not supported
print(tensor.dtype)
tensor

tf.Tensor(1, shape=(), dtype=int32)
1
(6,)
<dtype: 'int32'>


<tf.Tensor: shape=(6,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6], dtype=int32)>

In [ ]:
p = torch.tensor(t)
print(p.ndim)
print(p.shape)
print(p.itemsize)
print(p.size())    # not attribute but method
print(p.dtype)

1
torch.Size([6])
8
torch.Size([6])
torch.int64


In [ ]:
import tensorflow as tf

# 튜플 't'를 TensorFlow 상수 텐서로 변환
t = (1, 2, 3)
tensor = tf.constant(t)
print(tf.Variable(tensor))  # "tensor"를 TensorFlow 변수로 변환하고 출력


# print(tensor.ndim)  # 에러 발생: TensorFlow 텐서에는 ndim 속성이 없음
# print(tensor.shape)  # 정상 작동: shape는 TensorFlow 텐서에서 사용 가능
# print(tensor.itemsize)  # 에러 발생: TensorFlow 텐서에는 itemsize 속성이 없음
# print(tensor.size)  # 에러 발생: TensorFlow 텐서에는 size 속성이 없음

print(tensor.dtype)
print(tensor)  # 텐서를 출력


<tf.Variable 'Variable:0' shape=(6,) dtype=int32, numpy=array([1, 2, 3, 4, 5, 6], dtype=int32)>
<dtype: 'int32'>


<tf.Tensor: shape=(6,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6], dtype=int32)>

위의 코드에서 작동하지 않는 코드 수정

In [ ]:
import tensorflow as tf

# 튜플 't'를 TensorFlow 상수 텐서로 변환
t = (1, 2, 3)
tensor = tf.constant(t)
print(tf.Variable(tensor))  # "tensor"를 TensorFlow 변수로 변환하고 출력

# 수정된 부분들:
print(tensor.shape.ndims)  # 텐서의 차원 수 출력
print(tensor.shape)  # 텐서의 shape 출력
print(tf.size(tensor).numpy())  # 텐서의 요소 개수 출력

print(tensor.dtype)
print(tensor)  # 텐서를 출력


<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([1, 2, 3], dtype=int32)>
1
(3,)
3
<dtype: 'int32'>
tf.Tensor([1 2 3], shape=(3,), dtype=int32)


In [ ]:
import torch

# 튜플 't'를 PyTorch 텐서로 변환
t = (1, 2, 3)
p = torch.tensor(t)

print(p.ndim, type(p.ndim))  # 텐서의 차원 수 (rank)와 그 타입을 출력
# 출력 : 1 <class 'int'>
print(p.shape, type(p.shape))  # 텐서의 shape과 그 타입을 출력
#출력 : torch.Size([6]) <class 'torch.Size'>
print(p.itemsize, type(p.itemsize))  # 에러 발생: PyTorch 텐서에는 itemsize 속성이 없음
#출력 : 8 <class 'int'>
print(p.size(), type(p.size()))  # 텐서의 전체 요소 수와 그 타입을 출력
#출력 : torch.Size([6]) <class 'torch.Size'>
print(p.dtype, type(p.dtype))  # 텐서의 데이터 타입과 그 타입을 출력
#출력 :



1 <class 'int'>
torch.Size([6]) <class 'torch.Size'>
8 <class 'int'>
torch.Size([6]) <class 'torch.Size'>
torch.int64 <class 'torch.dtype'>


In [ ]:
print(np.array([1.,2.,3.]).dtype)
print(np.array([1,2,3]).dtype)
print(tf.constant([1.,2.,3.]).dtype)
print(tf.constant([1,2,3]).dtype)
print(torch.tensor([1.,2.,3.]).dtype)
print(torch.tensor([1,2,3]).dtype)



float64
int64
<dtype: 'float32'>
<dtype: 'int32'>
torch.float32
torch.int64


In [ ]:
# 중첩 리스트를 통해 다차원 배열 생성
a = np.array([range(i, i+3) for i in [2, 4, 6]])

print(a.ndim)  # 배열의 차원 수 출력
print(a.shape)  # 배열의 shape 출력
print(a.itemsize)  # 배열의 요소 하나의 크기(바이트 단위) 출력
print(a.size)  # 배열의 전체 요소 수 출력
print(a.dtype)  # 배열의 데이터 타입 출력

a  # 배열 자체를 출력


2
(3, 3)
8
9
int64


array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [ ]:
tensor = tf.constant(a)
print(tf.rank(tensor))
print(tensor.ndim)
# print(tensor.itemsize)  #error. not supported
# print(tensor.size)      #error. not supported
print(tensor.dtype)
tensor

tf.Tensor(2, shape=(), dtype=int32)
2
<dtype: 'int64'>


<tf.Tensor: shape=(3, 3), dtype=int64, numpy=
array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])>

In [ ]:
p = torch.tensor(a)
print(p.ndim)
print(p.shape)
print(p.itemsize)
print(p.size())    # not attribute but method
print(p.dtype)
p

2
torch.Size([3, 3])
8
torch.Size([3, 3])
torch.int64


tensor([[2, 3, 4],
        [4, 5, 6],
        [6, 7, 8]])

# 1-2. tensor를 특정값으로 **초기화하기**

In [ ]:
a = np.zeros((3,2))
# a = np.zeros(shape=(4,4),dtype=np.unit8)
print(a.dtype)
a

float64


array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [ ]:
a_tf = tf.zeros(shape=(3,2))
print(a_tf.dtype)
a_tf
#a_tf.numpy()

<dtype: 'float32'>


<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[0., 0.],
       [0., 0.],
       [0., 0.]], dtype=float32)>

In [ ]:
a_tf.numpy() #다시 numpy의 array로


array([[0., 0.],
       [0., 0.],
       [0., 0.]], dtype=float32)

In [ ]:
p = torch.zeros(size=(3,2))
print(p.dtype)
p

torch.float32


tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [ ]:
a = np.ones((4,2,3))
print(a.dtype)
a


float64


array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [ ]:
a_tf = tf.ones(shape=(4,2,3))
# a_tf = tf.ones((4,2), dtype=tf.int64)
print(a_tf.dtype)
a_tf

In [ ]:
xxx = np.eye(3)  # eye: 단위 행렬(identity matrix)을 생성하는 함수. 단위 행렬은 대각선 요소가 모두 1이고, 나머지 요소가 모두 0인 정방 행렬
print(xxx.dtype)
xxx

float64


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
a = np.full((1,3),255)  # full: 지정된 형태와 값으로 배열을 생성하는 함수. 여기서(1, 3) 크기의 배열을 생성하고, 모든 요소를 255로 채움
print(a.dtype)
a

int64


array([[255, 255, 255]])

numpy와 유사함!

In [ ]:
a_tf = tf.fill((1,3),255) # not full, but fill
print(a_tf.dtype) #default int32
a_tf

<dtype: 'int32'>


<tf.Tensor: shape=(1, 3), dtype=int32, numpy=array([[255, 255, 255]], dtype=int32)>

In [ ]:
p = torch.full((1,3),255)
print(p.dtype)
p

torch.int64


tensor([[255, 255, 255]])

텐서플로우와 넘파이의 차이점! full과 fill

# 1-3. 기존의 tensor와 같은 shape의 새로운 tensor생성

- 기존의 ndarray와 같은 shape를 가지는 ndarray 생성 (torch의 tensor도 유사.)
  * zeros_like, ones_like, and full_like
- tf의 경우는 다음과 같음.
  * zeoros_like, ones_like, and fill

In [ ]:
s = np.array([[1,2,3],[4,5,6]])
print(s.shape, a.dtype)

a = np.zeros_like(s)
print(a.shape, a.dtype)
a


(2, 3) int64
(2, 3) int64


array([[0, 0, 0],
       [0, 0, 0]])

In [ ]:
a = np.ones_like(s)
print(a.shape, a.dtype)
a

(2, 3) int64


array([[1, 1, 1],
       [1, 1, 1]])

In [ ]:
a = np.full_like(s,3.0)
print(a.dtype)
a

int64


array([[3, 3, 3],
       [3, 3, 3]])

In [ ]:
a = tf.fill(s.shape,3.0) # there is not fill_like
print(a.dtype)
a

<dtype: 'float32'>


<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[3., 3., 3.],
       [3., 3., 3.]], dtype=float32)>

# 1-4. 기타 다른 tensor 생성 방법들.

In [ ]:
print(range(0,10,1)) #range(start, stop, step)
print(np.arange(0,1,0.1))

list(range(0,10,1)) # range(0,10,1)을 보기 위한 방법

range(0, 10)
[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]


[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [ ]:
a = np.arange(0,24,2).reshape(3,4)
print(a.dtype)
a


int64


array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [ ]:
a_tf = tf.constant(tf.range(0,6,0.5),shape=(3,4))
print(a_tf.dtype)
a_tf

<dtype: 'float32'>


<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0. , 0.5, 1. , 1.5],
       [2. , 2.5, 3. , 3.5],
       [4. , 4.5, 5. , 5.5]], dtype=float32)>

In [ ]:
a = np.linspace(1,5,6) #numpy.linspace 함수는 시작 값과 끝 값 사이에서 지정된 수의 요소를 가진 배열을 생성
print(a.dtype)
print(a)
a_tf = tf.linspace(1,5,6)
print(a_tf.dtype)
b_tf = tf.dtypes.cast(a_tf,tf.float32) #a_tf라는 텐서를 tf.float32로 변환하여 새로운 텐서 b_tf에 저장
print(b_tf.dtype)
print(b_tf)
a_torch = torch.linspace(1,5,6)
print(a_torch.dtype)
print(a_torch)

float64
[1.  1.8 2.6 3.4 4.2 5. ]
<dtype: 'float64'>
<dtype: 'float32'>
tf.Tensor([1.  1.8 2.6 3.4 4.2 5. ], shape=(6,), dtype=float32)
torch.float32
tensor([1.0000, 1.8000, 2.6000, 3.4000, 4.2000, 5.0000])


In [ ]:
a = np.eye(5)
print(a.dtype)
print(a)
a_tf = tf.eye(5)
print(a_tf.dtype)
print(a_tf)
a_torch = torch.eye(5)
print(a_torch.dtype)
print(a_torch)

float64
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
<dtype: 'float32'>
tf.Tensor(
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]], shape=(5, 5), dtype=float32)
torch.float32
tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])


In [ ]:
# empty는 사용 비추, 초기화된 배열 생성인듯함.
a = np.empty((4,2))
print(a.dtype)
print(a)

# a_tf = tf.empty((4,2)) # not working. 초기화하지 않은 배열 생성.
# print(a_tf.dtype)
# print(a_tf)

a_torch = torch.empty((4,2))
print(a_torch.dtype)
print(a_torch)

float64
[[4.64265017e-310 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000]]
torch.float32
tensor([[-7.2286e+22,  3.0653e-41],
        [-7.2497e+22,  3.0653e-41],
        [ 0.0000e+00,  1.8750e+00],
        [ 0.0000e+00,  1.8750e+00]])


# **# 1-5.  난수로 구성된 tensor 생성.**



- numpy.random 와 torch
  * rand([d0 [,d1 [...,dn]) : 0~1 사이의 수들이 균일한 확률로 선택되어 반환됨.
      * d0, ..., dn : 난수로 구성된 ndarray의 shape를 지정하는 데 사용됨
  * randn([d0 [,d1 [..., dn]) : μ = 0, σ=1인 정규분포를 따르는 난수 반환.
- tensorflow
  * random.uniform(shape, minval, maxval)
  * random.normal(shape, mean, stddev)

In [ ]:
A = np. random.rand(3,4)
print(A.dtype)
A


float64


array([[0.79468726, 0.16109724, 0.01969602, 0.03898816],
       [0.4362321 , 0.55547089, 0.15572804, 0.92560364],
       [0.56268864, 0.56687295, 0.71376493, 0.37828509]])

In [ ]:
A_tf = tf.random.uniform(shape=(3,4), minval=0., maxval=1. )
A_tf

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0.01614976, 0.48922908, 0.5470562 , 0.53139293],
       [0.41002715, 0.9687065 , 0.5386946 , 0.58146036],
       [0.64093673, 0.49958086, 0.5709137 , 0.9310522 ]], dtype=float32)>

In [ ]:
A_torch = torch.rand(3,4)
print(A_torch.dtype)
A_torch

torch.float32


tensor([[0.5446, 0.7324, 0.0792, 0.3030],
        [0.2722, 0.5059, 0.0913, 0.7001],
        [0.4911, 0.6304, 0.3590, 0.5644]])

In [ ]:
A = np.random.randn(3,4) #normal distribution of which parameters are mean and standard deviation.
print(A.shape)
print(np.mean(A),np.std(A))
A

(3, 4)
-0.13274496606150715 1.0464429017838577


array([[-0.39530039, -0.71238713, -0.28439351,  0.60160549],
       [-0.2339714 ,  0.69515375, -1.45023146,  0.56493073],
       [ 0.66322011,  1.85584945, -0.67296407, -2.22445115]])

In [ ]:
A_tf = tf.random.normal(shape=(3,4),mean=0., stddev=1.0)
print(A_tf.shape)
print(tf.math.reduce_mean(A_tf),tf.math.reduce_std(A_tf))
A_tf


(3, 4)
tf.Tensor(-0.21457392, shape=(), dtype=float32) tf.Tensor(0.83589256, shape=(), dtype=float32)


<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[ 1.4692371e-01,  3.5444662e-02, -9.5163059e-01,  9.0270841e-01],
       [-1.2668747e+00,  9.3757480e-01,  1.7390382e-03, -5.2837539e-01],
       [ 4.0687418e-01, -5.9811950e-01,  2.9360521e-01, -1.9547569e+00]],
      dtype=float32)>

In [ ]:
A_torch = torch.randn(3,4)
print(A_torch.dtype)
print(torch.mean(A_torch),torch.std(A_torch))
A_torch

torch.float32
tensor(0.1543) tensor(0.7310)


tensor([[ 0.3985,  0.3914, -0.2638, -0.6972],
        [ 1.0801, -0.1166, -0.5902,  0.3724],
        [ 0.7069,  1.5204, -0.0471, -0.9030]])